### ISSUE TITLE
Twitter profile

### ISSUE THREAD

**Issue by carlosmassa** [btconometrics/BitcoinExchangeRateModel#1]
Hey Nick! Thanks for sharing your latest bitcoin exchange model!

Question completely unrelated: what happened to your twitter account? I can't read your tweets.

Hope all is fine with you!

![image](https://user-images.githubusercontent.com/47972273/195970367-38563b67-91db-4131-a0d5-1ee0ed17f60d.png)

**Comment by btconometrics** [comment]
I'll be back. Count on it.
